TEMPLATE = app
CONFIG += console
CONFIG += thread

include(censo_libs.pri)

SOURCES += main.cpp \
    Utils/definitions.cpp \
    Utils/metrics.cpp \
    Utils/linearinterpolation.cpp \
    Utils/bsplinepoly.cpp \
    OptimizationProblem/constraint.cpp \
    OptimizationProblem/constraintlinear.cpp \
    OptimizationProblem/constraintsine.cpp \
    OptimizationProblem/constraintset.cpp \
    OptimizationProblem/constraintquadratic.cpp \
    OptimizationProblem/constraintbilinear.cpp \
    OptimizationProblem/constraintpolynomial.cpp \
    OptimizationProblem/constraintexponential.cpp \
    OptimizationProblem/constraintbspline.cpp \
    OptimizationProblem/writetogams.cpp \
    SolverInterface/solveripopt.cpp \
    SolverInterface/interfaceipopt.cpp \
    SolverInterface/solverbonmin.cpp \
    SolverInterface/interfacebonmin.cpp \
    SolverInterface/solvergurobi.cpp \
    BranchAndBound/node.cpp \
    BranchAndBound/nodelist.cpp \
    BranchAndBound/branchandbound.cpp \
    BranchAndBound/bbutils.cpp \
    BranchAndBound/Branching/brancher.cpp \
    BranchAndBound/Branching/brancherinteger.cpp \
    BranchAndBound/Branching/branchercontinuous.cpp \
    BranchAndBound/Branching/branchercontinuousrandomvariable.cpp \
    BranchAndBound/Branching/branchercontinuousmostpromising.cpp \
    BranchAndBound/Branching/branchercontinuouslongestinterval.cpp \
    BranchAndBound/Branching/brancherintegermostfractional.cpp \
    BranchAndBound/Branching/brancheradmin.cpp \
    BranchAndBound/BoundsTightening/obbt.cpp \
    BranchAndBound/BoundsTightening/fbbt.cpp \
    Projects/JOGO/jogoexamples.cpp \
    Projects/PWL/pwlmodels.cpp \
    Projects/PWL/pwpmodels.cpp \
    Projects/FlowNetwork/flownetwork.cpp \
    TestProblems/testproblem.cpp \
    TestProblems/pop01.cpp \
    TestProblems/pop02.cpp \
    TestProblems/pop03.cpp \
    TestProblems/pop04.cpp \
    TestProblems/pop05.cpp \
    TestProblems/pop06.cpp \
    TestProblems/pop07.cpp \
    TestProblems/pop08.cpp \
    TestProblems/pop09.cpp \
    TestProblems/pop10.cpp \
    TestProblems/pop11.cpp \
    TestProblems/pop12.cpp \
    TestProblems/pop13.cpp \
    TestProblems/michalewicz.cpp \
    TestProblems/lp01.cpp \
    TestProblems/lp02.cpp \
    TestProblems/lp03.cpp \
    TestProblems/qp01.cpp \
    TestProblems/sixhumpcamel.cpp \
    TestProblems/bilinearrelaxationtest.cpp \
    TestProblems/asaadi1.cpp \
    TestProblems/linearintervalanalysistest.cpp \
    Test/testproblems.cpp \
    Test/unittests.cpp

HEADERS += \
    Utils/definitions.h \
    Utils/metrics.h \
    Utils/timer.h \
    Utils/linearsolvers.h \
    Utils/linearinterpolation.h \
    Utils/bsplinepoly.h \
    OptimizationProblem/variable.h \
    OptimizationProblem/constraint.h \
    OptimizationProblem/constraintlinear.h \
    OptimizationProblem/constraintsine.h \
    OptimizationProblem/constraintset.h \
    OptimizationProblem/constraintquadratic.h \
    OptimizationProblem/constraintbilinear.h \
    OptimizationProblem/constraintpolynomial.h \
    OptimizationProblem/constraintexponential.h \
    OptimizationProblem/constraintbspline.h \
    SolverInterface/solver.h \
    SolverInterface/solveripopt.h \
    SolverInterface/interfaceipopt.h \
    SolverInterface/solverbonmin.h \
    SolverInterface/interfacebonmin.h \
    SolverInterface/solvergurobi.h \
    BranchAndBound/node.h \
    BranchAndBound/nodelist.h \
    BranchAndBound/branchandbound.h \
    BranchAndBound/bbutils.h \
    BranchAndBound/Branching/brancher.h \
    BranchAndBound/Branching/brancherinteger.h \
    BranchAndBound/Branching/branchercontinuous.h \
    BranchAndBound/Branching/branchercontinuousrandomvariable.h \
    BranchAndBound/Branching/branchercontinuousmostpromising.h \
    BranchAndBound/Branching/branchercontinuouslongestinterval.h \
    BranchAndBound/Branching/brancherintegermostfractional.h \
    BranchAndBound/Branching/brancheradmin.h \
    BranchAndBound/BoundsTightening/boundstightener.h \
    BranchAndBound/BoundsTightening/obbt.h \
    BranchAndBound/BoundsTightening/fbbt.h \
    Projects/JOGO/jogoexamples.h \
    Projects/PWL/point.h \
    Projects/PWL/polytope.h \
    Projects/PWL/pwlmodels.h \
    Projects/PWL/triangulation.h \
    Projects/PWL/pwpmodels.h \
    Projects/FlowNetwork/graph.h \
    Projects/FlowNetwork/flownetwork.h \
    Projects/FlowNetwork/flownetworkdata.h \
    TestProblems/testproblem.h \
    TestProblems/alltestproblems.h \
    TestProblems/pop01.h \
    TestProblems/pop02.h \
    TestProblems/pop03.h \
    TestProblems/pop04.h \
    TestProblems/pop05.h \
    TestProblems/pop06.h \
    TestProblems/pop07.h \
    TestProblems/pop08.h \
    TestProblems/pop09.h \
    TestProblems/pop10.h \
    TestProblems/pop11.h \
    TestProblems/pop12.h \
    TestProblems/pop13.h \
    TestProblems/michalewicz.h \
    TestProblems/lp01.h \
    TestProblems/lp02.h \
    TestProblems/lp03.h \
    TestProblems/qp01.h \
    TestProblems/sixhumpcamel.h \
    TestProblems/bilinearrelaxationtest.h \
    TestProblems/asaadi1.h \
    TestProblems/linearintervalanalysistest.h \
    Test/unittests.h
